import { z } from 'astro:content';

export const ParkSchema = z.object({
  activities: z.array(z.string()),
  addresses: z.array(z.object({
    line1: z.string().nullish(),
    line2: z.string().nullish(),
    line3: z.string().nullish(),
    city: z.string().nullish(),
    stateCode: z.string().nullish(),
    provinceTerritoryCode: z.string().nullish(),
    postalCode: z.string().nullish(),
    type: z.string().nullish(),
  })),
  contacts: z.object({
    phoneNumbers: z.array(z.object({
      phoneNumber: z.string().nullish(),
      description: z.string().nullish(),
      extension: z.string().nullish(),
      type: z.string().nullish(),
    })).nullish(),
    emailAddresses: z.array(z.object({
      emailAddress: z.string().nullish(),
      description: z.string().nullish(),
    }).nullish()).nullish(),
  }).nullish(),
  description: z.string().nullish(),
  designation: z.string().nullish(),
  directionsInfo: z.string().nullish(),
  directionsUrl: z.string().url().nullish(),
  entranceFees: z.array(z.object({
    cost: z.union([z.string(),z.number()]).nullish(),
    description: z.string().nullish(),
    title: z.string().nullish(),
  })),
  entrancePasses: z.array(z.object({
    cost: z.union([z.string(),z.number()]).nullish(),
    description: z.string().nullish(),
    title: z.string().nullish(),
  })),
  fullName: z.string().nullish(),
  id: z.string().nullish(),
  images: z.array(z.object({
    credit: z.string().nullish(),
    altText: z.string().nullish(),
    title: z.string().nullish(),
    id: z.number().nullish(),
    caption: z.string().nullish(),
    url: z.string().url().nullish(),
  }).nullish()).nullish(),
  latitude: z.string().nullish(),
  longitude: z.string().nullish(),
  latLong: z.string().nullish(),
  multimedia: z.array(z.object({
    title: z.string().nullish(),
    id: z.string().nullish(),
    type: z.string().nullish(),
    url: z.string().url().nullish(),
  }).nullish()).nullish(),
  name: z.string().nullish(),
  operatingHours: z.array(z.object({
    name: z.string().nullish(),
    description: z.string().nullish(),
    standardHours: z.object({
      monday: z.string().nullish(),
      tuesday: z.string().nullish(),
      wednesday: z.string().nullish(),
      thursday: z.string().nullish(),
      friday: z.string().nullish(),
      saturday: z.string().nullish(),
      sunday: z.string().nullish(),
    }).nullish(),
    exceptions: z.array(z.object({
      name: z.string().nullish(),
      startDate: z.string().date().nullish(),
      endDate: z.string().date().nullish(),
      exceptionHours: z.object({
        monday: z.string().nullish(),
        tuesday: z.string().nullish(),
        wednesday: z.string().nullish(),
        thursday: z.string().nullish(),
        friday: z.string().nullish(),
        saturday: z.string().nullish(),
        sunday: z.string().nullish(),
      }).nullish(),
    }).nullish()).nullish(),
  }).nullish()).nullish(),
  parkCode: z.string().nullish(),
  relevanceScore: z.number().nullish(),
  states: z.string().nullish(),
  topics: z.array(z.string()),
  url: z.string().url().nullish(),
  weatherInfo: z.string().nullish(),
});

export type ParkSchema = z.infer<typeof ParkSchema>